micronaut:
  application:
    name: mysqlApp
datasources:
  default:
    url: jdbc:mysql://localhost:3306/exampleDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'admin1234'
    schema-generate: none
    dialect: MYSQL

