micronaut:
  application:
    name: mysqlApp
datasources:
  default:
    url: jdbc:mysql://mysqldb/userdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'admin1234'
    schema-generate: none
    dialect: MYSQL

